# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='free', max_length=255),
        ),
    ]
