# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180324_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firebase_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
