# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180421_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rating_sum',
            field=models.FloatField(default=0),
        ),
    ]
