# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.PositiveSmallIntegerField(choices=[(1, 'truck'), (2, 'pickup'), (3, 'van'), (4, 'eco_car'), (5, 'SUV'), (6, 'sport_car'), (7, 'pickup')])),
                ('plate', models.CharField(max_length=30)),
                ('_model', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_location', models.TextField(blank=True, null=True)),
                ('depart_latitute', models.TextField(blank=True, null=True)),
                ('depart_longtitute', models.TextField(blank=True, null=True)),
                ('arrive_location', models.TextField(blank=True, null=True)),
                ('arrive_latitute', models.TextField(blank=True, null=True)),
                ('arrive_longtitute', models.TextField(blank=True, null=True)),
                ('current_location', models.TextField(blank=True, null=True)),
                ('current_latitute', models.TextField(blank=True, null=True)),
                ('current_longtitute', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Car')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
