# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_longtitude', models.FloatField(blank=True, max_length=255, null=True)),
                ('pickup_lattitude', models.FloatField(blank=True, max_length=255, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_longtitude', models.FloatField(blank=True, max_length=255, null=True)),
                ('destination_lattitude', models.FloatField(blank=True, max_length=255, null=True)),
                ('current_longtitude', models.FloatField(blank=True, max_length=255, null=True)),
                ('current_lattitude', models.FloatField(blank=True, max_length=255, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
