# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='pickup_lattitude',
            new_name='start_lattitude',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='pickup_location',
            new_name='start_location',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='pickup_longtitude',
            new_name='start_longtitude',
        ),
    ]
