# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travel_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='car_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
