# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20180205_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='travel',
            name='status',
            field=models.CharField(default='doing', max_length=255),
        ),
    ]
