# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='timeupdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
