# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20171209_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'truck'), (2, 'pickup'), (3, 'van'), (4, 'eco_car'), (5, 'SUV'), (6, 'sport_car'), (7, 'pickup')], default='1'),
        ),
    ]
