# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_request__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='receiver_tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination_lattitude',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination_longtitude',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='pickup_lattitude',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='pickup_longtitude',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
