# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20171213_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='doing', max_length=255),
        ),
    ]
