# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20180205_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
