# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_request_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='request',
            name='timeupdate',
        ),
        migrations.AddField(
            model_name='request',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 4, 35, 11, 334955, tzinfo=utc), verbose_name='expire'),
        ),
    ]
