# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_auto_20180416_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tracking_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 9, 6, 7, 250702, tzinfo=utc), verbose_name='expire'),
        ),
    ]
