# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_auto_20180417_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='route_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 13, 54, 37, 536069, tzinfo=utc), verbose_name='expire'),
        ),
    ]
