# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-21 04:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_auto_20180417_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 4, 5, 14, 968778, tzinfo=utc), verbose_name='expire'),
        ),
    ]
