# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
