# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0005_auto_20180324_1704'),
        ('request', '0011_auto_20180416_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_id', models.IntegerField(blank=True, max_length=255, null=True)),
                ('signatute', models.ImageField(blank=True, null=True, upload_to='signature')),
                ('status', models.CharField(default='doing', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel')),
            ],
        ),
    ]
