# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_detail', '0002_remove_matching_detail_signatute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching_detail',
            name='status',
            field=models.CharField(default='matched', max_length=255),
        ),
    ]
